# Copyright (c) 2022-2026, The Isaac Lab Project Developers.
# All rights reserved.
# Original code is licensed under BSD-3-Clause.
#
# Copyright (c) 2025-2026, The Loco Lab Project Developers.
# All rights reserved.
# Modifications are licensed under BSD-3-Clause.

asset_path: /home/agnel/unitree/github/unitree_ros/robots/h1_2_description/h1_2_handless.urdf
usd_dir: /home/agnel/unitree/github/unitree_ros/robots/h1_2_description/h1_2_handless
usd_file_name: null
force_usd_conversion: false
make_instanceable: true
fix_base: false
root_link_name: null
link_density: 0.0
merge_fixed_joints: true
convert_mimic_joints_to_normal_joints: false
joint_drive:
  drive_type: force
  target_type: position
  gains:
    stiffness: null
    damping: null
collider_type: convex_hull
self_collision: true
replace_cylinders_with_capsules: false
collision_from_visuals: false
func: isaaclab.sim.spawners.from_files.from_files:spawn_from_urdf
visible: true
semantic_tags: null
copy_from_source: true
mass_props: null
deformable_props: null
rigid_props:
  rigid_body_enabled: null
  kinematic_enabled: null
  disable_gravity: false
  linear_damping: 0.0
  angular_damping: 0.0
  max_linear_velocity: 100.0
  max_angular_velocity: 100.0
  max_depenetration_velocity: 1.0
  max_contact_impulse: null
  enable_gyroscopic_forces: null
  retain_accelerations: false
  solver_position_iteration_count: null
  solver_velocity_iteration_count: null
  sleep_threshold: null
  stabilization_threshold: null
collision_props: null
activate_contact_sensors: true
scale: null
articulation_props:
  articulation_enabled: null
  enabled_self_collisions: true
  solver_position_iteration_count: 4
  solver_velocity_iteration_count: 0
  sleep_threshold: null
  stabilization_threshold: null
  fix_root_link: null
fixed_tendons_props: null
spatial_tendons_props: null
joint_drive_props: null
visual_material_path: material
visual_material: null
##
# Generated by UrdfConverter on 2025-08-25 at 15:38:53.
##
